version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "authCodeChallengeLogin"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-670nzt8sx3qo"
s3_prefix = "authCodeChallengeLogin"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
